### ISSUE TITLE
Add an about.html file in all bundles and define a branding bundle at least for RCP part.

### ISSUE THREAD

**Issue by arcadmlafon** [ARCAD-Software/AFS#24]
Some bundles do not include the documentation file about.html (see /bundles/common/crypt for an examble).

And the AFS Client/RCP features do not have a branding bundle.

**Comment by mhx-arcad** [comment]
All the about.html (with approximate description for each bundle) and modified build.properties to integrate the about.html have been created in all bundles in this repository (server, client and common).
cf commit [f2072a153426c0632fa62a390859d4ff61d2b30a](https://github.com/ARCAD-Software/AFS/commit/f2072a153426c0632fa62a390859d4ff61d2b30a)
