### ISSUE TITLE
Add the connection  bundle c.a.s.restfule.connection.config

### ISSUE THREAD

**Issue by arcadmlafon** [ARCAD-Software/AFS#25]
The Config connection may be required to connect to the AFS Server when there is not other configuration mode enabled (Database nor LDAP).

**Comment by mhx-arcad** [comment]
Done in commit [204fc92d6e47692f33fb342512ead20d1793a850](https://github.com/ARCAD-Software/AFS/commit/204fc92d6e47692f33fb342512ead20d1793a850)
