### ISSUE TITLE
[Metadata] NPE when trying to delete entities with a criteria

### ISSUE THREAD

**Issue by pjvilloud** [ARCAD-Software/AFS#71]
The `new JoinsMap(null)` causes NullPointerException. 

https://github.com/ARCAD-Software/AFS/blob/2e43c1ca6f84bc34dbf74c304ace198cf6d270a5/bundles/server/metadata.mapper.sql/src/com/arcadsoftware/metadata/sql/MapperSQLService.java#L1359

I stumble upon this issue while trying to delete entities with a criteria.

**Comment by arcadmlafon** [comment]
I need more information, which criteria is used ?
