### ISSUE TITLE
[Metadata SQL] ChangedCriteria usage leads to ClassCastException

### ISSUE THREAD

**Issue by pjvilloud** [ARCAD-Software/AFS#72]
In MapperSQLService, there is a cast trying to cast a ChangedCriteria into a BetweenCriteria

https://github.com/ARCAD-Software/AFS/blob/2e43c1ca6f84bc34dbf74c304ace198cf6d270a5/bundles/server/metadata.mapper.sql/src/com/arcadsoftware/metadata/sql/MapperSQLService.java#L1010-L1018

**Comment by arcadmlafon** [comment]
fixed and released.

@cyangArcad you can add "Fix #72" in your commit comment to automatically add a reference to an issue and close it when a bug is corrected.
